SELECT STEELGRADE ,COUNT(STEELGRADE) AS CON  FROM AP_STRIP_PDI GROUP BY STEELGRADE  ORDER BY CON DESC


SELECT WS_GAP_FBK ,ROLLGAP_ZERO ,ROLLGAP_TRUE ,ROLL_FORCE,ROLL_FORCE / MILLSTRETCH_ROLL GANGDU FROM  AP.SCC_POST_ROLLGAP WHERE STRIP_NO = 220005203800 ORDER BY STAND_NO ,SEG_NO ;


SELECT WS_GAP_FBK ,ROLLGAP_ZERO ,ROLLGAP_TRUE ,ROLL_FORCE,ROLL_FORCE / MILLSTRETCH_ROLL GANGDU FROM  AP.SCC_POST_ROLLGAP WHERE STRIP_NO = 220005203800 ORDER BY STAND_NO ,SEG_NO ;