SELECT 
--pdi.STRIPNO STRIP_NO,pdi.sfc,
POSTFORCE.STRIP_WIDTH,
PDI.CARBON,
pdi.MANGANESE,
PDI.SILICON,
PDI.NIOBIUM,
PDI.CHROMIUM,
PDI.VANADIUM,
PDI.MOLYBDENUM,
PDI.NIOBIUM,
PDI.TITANIUM,
PDI.COPPER,
POSTFORCE.ROLL_DIAM,
POSTFORCE.REL_REDU,
POSTFORCE.ENTRY_THICK,
POSTFORCE.EXIT_THICK,
POSTFORCE.ENTRY_TEMP,
POSTFORCE.CIRC_SPEED  ,
--CALFORCE.ENTRY_TENSION ENTRY_TENSION_CAL,
--CALFORCE.EXIT_TENSION EXIT_TENSION_CAL,
SUB.FORCE+SUB.FORCE_WS FORCE
--to_char(PDI.TOC,'yyyy/mm/dd hh:mm:ss') TOC
FROM AP.AP_STRIP_PDI  AS PDI 
JOIN AP.SCC_FMSTRIP AS FMSTRIP  ON PDI.SFC  = 1001 AND  FMSTRIP.STRIP_NO =PDI.STRIPNO AND pDI.TOC<=to_date('2024-10-01','yyyy-mm-dd') AND pDI.TOC>=to_date('2021-01-02','yyyy-mm-dd')
JOIN AP.SCC_ACT_FMSEG AS ACT ON act.SEG_NO =3 AND ACT.STRIP_NO =PDI.STRIPNO 
JOIN AP.SCC_CALC_ROLLFORCE AS CALFORCE ON CALFORCE.STRIP_NO =PDI.STRIPNO AND (CALFORCE.STAND_NO = 6)
JOIN AP.SCC_POST_ROLLGAP AS postroll ON postroll.STRIP_NO = pdi.STRIPNO AND postroll.STAND_NO = calforce.STAND_NO AND postroll.SEG_NO = act.SEG_NO
JOIN AP.SCC_POST_ROLLFORCE AS POSTFORCE ON  postforce.STRIP_NO = pdi.STRIPNO  AND postforce.SEG_NO = act.SEG_NO AND postforce.STAND_NO =calforce.STAND_NO 
JOIN AP.SCC_ACT_FMSEGACT_SUB AS SUB ON SUB.STRIP_NO = pdi.STRIPNO AND SUB.SEG_NO =act.SEG_NO AND SUB.STAND_NO = calforce.STAND_NO 
JOIN AP.SCC_POST_TEMP AS POSTTEMP ON POSTTEMP.STRIP_NO =PDI.STRIPNO AND POSTTEMP.STAND_NO =CALFORCE.STAND_NO  AND POSTTEMP.SEG_NO =ACT.SEG_NO 
JOIN AP.SCC_CALC_TEMP AS CALTEMP ON CALTEMP.STRIP_NO =PDI.STRIPNO AND CALTEMP.STAND_NO =CALFORCE.STAND_NO
JOIN AP.AP_STRIP_STATIS AS STATIS ON STATIS.ITEM = 'tempR2Exit' AND  STATIS.STRIPNO  = PDI.STRIPNO 
JOIN AP.RMC_ACT_RMPASS   AS PASS ON PASS.STRIPNO  = PDI.STRIPNO AND PASS.STANDNO =2 AND PASS.PASSNO  = 3 
JOIN AP.RMC_ACT_R2LAST AS R2LAST ON  R2LAST .STRIPNO =PDI.STRIPNO 
ORDER BY PDI.TOC ,  PDI.STRIPNO , CALFORCE.STAND_NO



--SELECT SFC,COUNT(SFC) C FROM AP.AP_STRIP_PDI GROUP BY SFC ORDER BY C DESC ;

                                