SELECT LIST+1 FROM (SELECT 	AP.SCC_POST_ROLLGAP.STRIP_NO ,AP.SCC_POST_ROLLGAP.CORR_ZEROPOINT_USE,TOC,ROWNUM LIST 
FROM AP.SCC_POST_ROLLGAP
where  	 AP.SCC_POST_ROLLGAP.STRIP_NO =(SELECT ap.SCC_FMSTRIP.STRIP_NO 
FROM AP.SCC_FMSTRIP
where  
AP.SCC_FMSTRIP.TOC > (select TOC - 30 Minutes	 from AP.SCC_FMSTRIP where AP.SCC_FMSTRIP.STRIP_NO = 220030000800) 	
AND  AP.SCC_FMSTRIP.TOC < (select TOC	 from AP.SCC_FMSTRIP where AP.SCC_FMSTRIP.STRIP_NO = 220030000800) 	)
AND AP.SCC_POST_ROLLGAP.SEG_NO = 3 AND AP.SCC_POST_ROLLGAP.STAND_NO =7 
ORDER BY TOC DESC fetch first 5 rows ONLY) WHERE CORR_ZEROPOINT_USE=0 

