SELECT AP.GAUGE_SAMPLE.DATASEQ  FROM AP.GAUGE_SAMPLE WHERE ITEM LIKE 'thicknessF7Exit%' AND   AP.GAUGE_SAMPLE.STRIPNO =  220151202200

TRUNCATE THICK_SCALE;

SELECT * FROM THICK_SCALE_2;
create table ap.thick_scale_2(
strip_no varchar(50),THICK_SCALE integer
)

SELECT * FROM AP.THICK_SCALE order by THICK_SCALE