SELECT PASS.ROLLEDSEQ ,(ACT.FM_THICK - PDI.FMOUTTHICK) AS DELTA  FROM SCC_CALC_PASS PASS,SCC_ACT_FMSEG ACT,AP_STRIP_PDI PDI WHERE PASS.STRIPNO = ACT.STRIP_NO AND PDI.STRIPNO  = PASS.STRIPNO 
AND ACT.SEG_NO = 1  ORDER BY PASS.TOC



SELECT TIMESTAMPDIFF(2,CHAR(TIMESTAMP(ACT.TOC)-TIMESTAMP('2021-10-28 08:00:00'))) AS UNIX_TOC ,
(ACT.FM_THICK - PDI.FMOUTTHICK) AS DELTA 
FROM SCC_ACT_FMSEG ACT,AP_STRIP_PDI PDI 
WHERE  ACT.STRIP_NO  = PDI.STRIPNO 
AND ACT.SEG_NO = 1  
AND ACT.TOC <= to_date('2022-01-01', 'yyyy-mm-dd') 
AND ACT.TOC >= to_date('2021-11-01', 'yyyy-mm-dd') ORDER BY UNIX_TOC
