SELECT pdi.STRIPNO STRIP_NO ,postforce.STAND_NO,pdi.sfc SFC,fmstrip.THICK_CLASS, fmstrip.WIDTH_CLASS ,fmstrip.TEMP_CLASS ,
POSTFORCE.STRIP_WIDTH,
POSTFORCE.ENTRY_THICK,
POSTFORCE.EXIT_THICK,
POSTFORCE.STRIP_SPEED,
POSTFORCE.ENTRY_TEMP,
POSTFORCE.ROLL_DIAM,
CALFORCE.ENTRY_TENSION ENTRY_TENSION_CAL,
CALFORCE.EXIT_TENSION EXIT_TENSION_CAL,
PDI.CARBON,PDI.SILICON,PDI.MANGANESE,PDI.PHOSPHORUS,PDI.SULPHUR,
PDI.COPPER,PDI.NICKEL,PDI.CHROMIUM,PDI.ARSENIC,PDI.TIN,PDI.NIOBIUM,
PDI.VANADIUM,PDI.ALUMINIUM,PDI.TITANIUM,PDI.MOLYBDENUM,PDI.BORON,PDI.TUNGSTEN,
PDI.CALCIUM,PDI.HYDROGEN,PDI.OXYGEN,PDI.NITROGEN,PDI.SOL_ALUMINIUM,PDI.ANTIMONY,
SUB.FORCE+SUB.FORCE_WS FORCE,
to_char(PDI.TOC,'yyyy/mm/dd hh:mm:ss') TOC
FROM AP.AP_STRIP_PDI  AS PDI 
JOIN AP.SCC_FMSTRIP AS FMSTRIP  ON FMSTRIP.STRIP_NO =PDI.STRIPNO AND pDI.TOC<=to_date('2022-12-31','yyyy-mm-dd') AND pDI.TOC>=to_date('2020-01-01','yyyy-mm-dd')
JOIN AP.SCC_CALC_ROLLFORCE AS CALFORCE ON CALFORCE.STRIP_NO =PDI.STRIPNO AND (CALFORCE.STAND_NO = 6)
JOIN AP.SCC_POST_ROLLFORCE AS POSTFORCE ON  postforce.STRIP_NO = pdi.STRIPNO  AND postforce.SEG_NO = 3 AND postforce.STAND_NO =calforce.STAND_NO 
JOIN AP.SCC_ACT_FMSEGACT_SUB AS SUB ON SUB.STRIP_NO = pdi.STRIPNO AND SUB.SEG_NO = postforce.SEG_NO AND SUB.STAND_NO = calforce.STAND_NO 
ORDER BY PDI.TOC ,  PDI.STRIPNO , CALFORCE.STAND_NO