--SELECT 	AP.SCC_POST_ROLLGAP.STRIP_NO ,AP.SCC_POST_ROLLGAP.CORR_ZEROPOINT_USE,TOC,ROWNUM LIST 		
--FROM AP.SCC_POST_ROLLGAP 	where  
--AP.SCC_POST_ROLLGAP.TOC > (select TOC - 30 Minutes	 from AP.SCC_FMSTRIP where AP.SCC_FMSTRIP.STRIP_NO = 220030000800) 	
--AND  AP.SCC_POST_ROLLGAP.TOC < (select TOC	 from AP.SCC_FMSTRIP where AP.SCC_FMSTRIP.STRIP_NO = 220030000800) 	
--AND AP.SCC_POST_ROLLGAP.SEG_NO = 3 AND AP.SCC_POST_ROLLGAP.STAND_NO = 7 AND AP.SCC_POST_ROLLGAP.CORR_ZEROPOINT_USE = 0 	
--ORDER BY TOC DESC fetch first 5 rows ONLY

select STRIP_WIDTH from ap.scc_post_rollforce where ap.scc_post_rollforce.STRIP_NO = 220146900600 


select FMOUTWIDTH,FMOUTWIDTHTOLPLUS from ap.AP_STRIP_PDI asp WHERE asp.STRIPNO = 220146900600 

ALTER TABLE AP.THICK_SCALE ADD THICK_SCALE int

-- AP.GAUGE_SAMPLE.STRIPNO, AP.AP_STRIP_PDI.FMOUTTHICK, 
SELECT max(length(AP.GAUGE_SAMPLE.DATASEQ))  FROM AP.GAUGE_SAMPLE, AP.AP_STRIP_PDI WHERE ITEM LIKE 'thicknessF7Exit' AND  AP.GAUGE_SAMPLE.TOM <= to_date('2025-07-01', 'yyyy-mm-dd') AND AP.GAUGE_SAMPLE.TOM >= to_date('2020-06-01', 'yyyy-mm-dd') AND  AP.GAUGE_SAMPLE.STRIPNO = AP.AP_STRIP_PDI.STRIPNO


INSERT INTO AP.THICK_SCALE values(22222020, 7);

SELECT AP.GAUGE_SAMPLE.STRIPNO, AP.AP_STRIP_PDI.FMOUTTHICK, AP.GAUGE_SAMPLE.DATASEQ  FROM AP.GAUGE_SAMPLE, AP.AP_STRIP_PDI WHERE ITEM LIKE 'thicknessF7Exit' AND  AP.GAUGE_SAMPLE.TOM <= to_date('2021-07-02', 'yyyy-mm-dd') AND AP.GAUGE_SAMPLE.TOM >= to_date('2021-06-01', 'yyyy-mm-dd') AND  AP.GAUGE_SAMPLE.STRIPNO = AP.AP_STRIP_PDI.STRIPNO

CREATE TABLE "AP      "."THICK_SCALE"  (
		  "STRIP_NO" VARCHAR(50 OCTETS) , 
		  "THICK_SCALE" INTEGER )   
		 IN "USERSPACE1"  
		 ORGANIZE BY ROW;


TRUNCATE  AP.THICK_SCALE ;

SELECT AP.GAUGE_SAMPLE.STRIPNO, AP.AP_STRIP_PDI.FMOUTTHICK, AP.GAUGE_SAMPLE.DATASEQ  FROM AP.GAUGE_SAMPLE, AP.AP_STRIP_PDI WHERE ITEM LIKE 'thicknessF7Exit%' AND  AP.GAUGE_SAMPLE.TOM <= to_date('2021-08-01', 'yyyy-mm-dd') AND AP.GAUGE_SAMPLE.TOM >= to_date('2021-07-01', 'yyyy-mm-dd') AND  AP.GAUGE_SAMPLE.STRIPNO = AP.AP_STRIP_PDI.STRIPNO