SELECT AP.GAUGE_SAMPLE.STRIPNO , AP.AP_STRIP_PDI.FMOUTTHICK , AP.GAUGE_SAMPLE.DATASEQ  FROM AP.GAUGE_SAMPLE, AP.AP_STRIP_PDI  
WHERE ITEM LIKE 'thicknessF7Exit%' AND  AP.GAUGE_SAMPLE.TOM <=to_date('2024-12-01','yyyy-mm-dd') AND AP.GAUGE_SAMPLE.TOM>=to_date('2020-11-01','yyyy-mm-dd')
AND  AP.GAUGE_SAMPLE.STRIPNO = AP.AP_STRIP_PDI.STRIPNO  AND AP.GAUGE_SAMPLE.STRIPNO = 220006602900

SELECT AP.GAUGE_SAMPLE.STRIPNO , AP.GAUGE_SAMPLE.ITEM ,AP.AP_STRIP_PDI.FMOUTWIDTH  , AP.GAUGE_SAMPLE.DATASEQ  FROM AP.GAUGE_SAMPLE, AP.AP_STRIP_PDI  
WHERE (ITEM LIKE 'widthF7Exit') AND  AP.GAUGE_SAMPLE.TOM <=to_date('2024-12-01','yyyy-mm-dd') AND AP.GAUGE_SAMPLE.TOM>=to_date('2020-11-01','yyyy-mm-dd')
AND  AP.GAUGE_SAMPLE.STRIPNO = AP.AP_STRIP_PDI.STRIPNO  AND AP.GAUGE_SAMPLE.STRIPNO = 220002002700

SELECT * FROM AP.AP_MILLSAMPLE WHERE STRIPNO = '220002002700';
 
 
 SELECT AP.GAUGE_SAMPLE.STRIPNO , AP.GAUGE_SAMPLE.ITEM ,AP.AP_STRIP_PDI.FMOUTWIDTH  ,CAST(AP.GAUGE_SAMPLE.DATASEQ as VARCHAR(15130) CCSID UNICODE) as CHAR_FLD, LENGTH ( AP.GAUGE_SAMPLE.DATASEQ)  FROM AP.GAUGE_SAMPLE, AP.AP_STRIP_PDI  
WHERE (ITEM LIKE 'tempF7ExitMFG') AND  AP.GAUGE_SAMPLE.TOM <=to_date('2024-12-01','yyyy-mm-dd') AND AP.GAUGE_SAMPLE.TOM>=to_date('2020-11-01','yyyy-mm-dd')
AND  AP.GAUGE_SAMPLE.STRIPNO = AP.AP_STRIP_PDI.STRIPNO  AND AP.GAUGE_SAMPLE.STRIPNO = 220002400100

SELECT  AP.GAUGE_SAMPLE.STRIPNO , LENGTH(AP.GAUGE_SAMPLE.DATASEQ) len FROM AP.GAUGE_SAMPLE WHERE (ITEM LIKE 'tempF7ExitMFG') ORDER BY len DESC ;


select * from ( select flowId,id,convert(data using utf8) as url from node ) as t where url like '%education_bussiness.sh%'




SELECT SCC_ACT_FMSEG.STRIP_NO,nvl( AP.THICK_SCALE.THICK_SCALE,0)  FROM AP.SCC_ACT_FMSEG INNER JOIN AP.THICK_SCALE  ON SCC_ACT_FMSEG.STRIP_NO =  THICK_SCALE.STRIP_NO AND SEG_NO = 1 AND  trunc(TOM) = TO_DATE('2021-12-08','yyyy-mm-dd')  ORDER BY TOM;



SELECT SCC_ACT_FMSEG.STRIP_NO FROM AP.SCC_ACT_FMSEG WHERE SEG_NO = 1 AND  trunc(TOM) = TO_DATE('2021-12-08','yyyy-mm-dd')  ORDER BY TOM;


SELECT THICK_SCALE FroM THICK_SCALE WHERE STRIP_NO = 22000650010


SELECT nvl(HICK_SCALE,0) FORM THICK_SCALE WHERE STRIP_NO = 220006500100


SELECT AP.GAUGE_SAMPLE.STRIPNO , AP.GAUGE_SAMPLE.ITEM ,AP.AP_STRIP_PDI.FMOUTTHICK  , AP.AP_STRIP_PDI.FMOUTTHICKTOLPLUS,CAST(AP.GAUGE_SAMPLE.DATASEQ as VARCHAR(15130) CCSID UNICODE) as CHAR_FLD, LENGTH ( AP.GAUGE_SAMPLE.DATASEQ) ,nvl( AP.THICK_SCALE.THICK_SCALE,0) FROM AP.GAUGE_SAMPLE 
inner join AP.AP_STRIP_PDI   on (ITEM LIKE 'thicknessF7Exit') AND  AP.GAUGE_SAMPLE.STRIPNO = AP.AP_STRIP_PDI.STRIPNO  AND AP.GAUGE_SAMPLE.STRIPNO = 220172400100
left join AP.THICK_SCALE on AP.GAUGE_SAMPLE.STRIPNO = AP.THICK_SCALE.STRIP_NO





