SELECT SSS.*,ACT_SS.FM_TEMP - PDI_SS.FMTEMP TEMP_DELTA_LASTGAP,ACT_SUB_SS.FORCE+ACT_SUB_SS.FORCE_WS-POST_ROLL.ROLL_FORCE TEMP_FORCE_ROLL,
(SSS.S_UNIX_TOC - TIMESTAMPDIFF(2,CHAR(TIMESTAMP(ACT_SS.TOC)-TIMESTAMP('2021-06-28 08:00:00'))) ) AS interval_time_force,
SSS.S_FM_THICK - SSS.S_FMOUTTHICH AIM 
FROM
(
SELECT                ----------------------组合
	S.STRIPNO,
	S.LAST_STRIP_NO,
	AVG(S.SEG_NO) AS S_SEG_NO,
	AVG(S.SFC) AS S_SFC,
	AVG(S.FM_THICK) AS S_FM_THICK,
	AVG(S.FMOUTTHICK) AS S_FMOUTTHICH,
	LISTAGG(S.ROLL_FORCE,',') AS S_ROLL_FORCE,
	LISTAGG(S.CORR_FORCE_STAND,',') AS S_CORR_FORCE_STAND,
	LISTAGG(S.ROLL_SPEED,',') AS S_ROLL_SPEED,
	LISTAGG(S.ENTRY_THICK,',') AS S_ENTRY_THICK,
	LISTAGG(S.EXIT_THICK,',') AS S_EXIT_THICK,
	LISTAGG(S.ENTRY_TEMP,',') AS S_ENTRY_TEMP,
	LISTAGG(S.STRIP_WIDTH,',') AS S_STRIP_WIDTH,
	LISTAGG(S.ROLLGAP_SET,',') AS S_ROLLGAP_SET,
	LISTAGG(S.MILLSTRETCH_ROLL,',') AS S_MILLSTRETCH_ROLL,
	LISTAGG(S.CORR_ZEROPOINT,',') AS S_CORR_ZEROPOINT,
	LISTAGG(S.ROLLWEAR,',') AS S_ROLLWEAR,
	AVG(S.ROLLEDSEQ) AS S_ROLLEDSEQ,
--	AVG(S.INHER_STRIPNO_ROLLFORCE) AS S_INHER_STRIPNO_ROLLFORCE,
	S.UNIX_TOC AS S_UNIX_TOC,---------------------------------------------------
	S.FMOUTWIDTH AS S_FMOUTWIDTH,
	S.LAST_STRIP_NO_TEMP
FROM
	(
	SELECT
		PDI.STRIPNO ,
		PASS.LAST_STRIP_NO LAST_STRIP_NO,
		act.SEG_NO ,
		ROLLFORCE.STAND_NO ,
		PDI.SFC ,
		ACT.FM_THICK ,
		PDI.FMOUTTHICK ,
		ROLLFORCE.ROLL_FORCE ,
		ROLLFORCE.CORR_FORCE_STAND ,
		ROLLFORCE.ENTRY_THICK ,
		ROLLFORCE.EXIT_THICK ,
		ROLLFORCE.ENTRY_TEMP ,
		GAP.ROLL_SPEED ,
		GAP.STRIP_WIDTH ,
		GAP.ROLLGAP_SET ,
		GAP.MILLSTRETCH_ROLL ,
		GAP.ROLLWEAR ,
		GAP.CORR_ZEROPOINT ,
		PDI.FMOUTWIDTH ,
		PASS.ROLLEDSEQ ,
--		PASS.INHER_STRIPNO_ROLLFORCE,
		TIMESTAMPDIFF(2,CHAR(TIMESTAMP(ACT.TOC)-TIMESTAMP('2021-06-28 08:00:00'))) AS UNIX_TOC,
		PASS.INHER_STRIPNO_TEMP LAST_STRIP_NO_TEMP
	FROM
			AP_STRIP_PDI PDI,
			SCC_CALC_ROLLFORCE ROLLFORCE,
			SCC_CALC_ROLLGAP GAP,
			SCC_CALC_PASS PASS,
			SCC_CALC_TEMP TEMP,
			SCC_ACT_FMSEG ACT
	WHERE
			ROLLFORCE.STRIP_NO = PDI.STRIPNO
		AND GAP.STRIP_NO = PDI.STRIPNO
		AND PASS.STRIPNO = PDI.STRIPNO
		AND TEMP.STRIP_NO = PDI.STRIPNO
		AND ACT.STRIP_NO = PDI.STRIPNO
		AND ACT.SEG_NO = 1
		AND GAP.STAND_NO = ROLLFORCE.STAND_NO
		AND TEMP.STAND_NO = GAP.STAND_NO
		AND PDI.TOC <= to_date('2022-01-01', 'yyyy-mm-dd')
		AND PDI.TOC >= to_date('2021-06-01', 'yyyy-mm-dd')
		ORDER BY ACT.TOC
	) AS S 
GROUP BY
		S.STRIPNO ,S.LAST_STRIP_NO,S.LAST_STRIP_NO_TEMP,S.UNIX_TOC,S.FMOUTWIDTH
) AS SSS , AP_STRIP_PDI AS PDI_SS,SCC_ACT_FMSEG AS ACT_SS,SCC_POST_ROLLFORCE AS POST_ROLL,SCC_ACT_FMSEGACT_SUB  ACT_SUB_SS
		WHERE PDI_SS.STRIPNO = SSS.LAST_STRIP_NO_TEMP AND ACT_SS.STRIP_NO = SSS.LAST_STRIP_NO_TEMP AND ACT_SS.SEG_NO = 1
		AND POST_ROLL.STRIP_NO = PDI_SS.STRIPNO AND POST_ROLL.SEG_NO = 1 AND POST_ROLL.STAND_NO = 7
		AND ACT_SUB_SS.STRIP_NO = PDI_SS.STRIPNO AND ACT_SUB_SS.SEG_NO = 1 AND ACT_SUB_SS.STAND_NO = 7
		
		
SELECT STRIP_NO  FROM SCC_ACT_FMSEG WHERE SEG_NO ;
SELECT THICK_SCALE.* ,SCC_CALC_PASS.TOC FROM SCC_CALC_PASS,THICK_SCALE WHERE  SCC_CALC_PASS.STRIPNO = THICK_SCALE.STRIP_NO ORDER BY TOC;     --1/6
SELECT * FROM SCC_CALC_PASS;


---查上一块
SELECT STRIPNO ,SCC_CALC_PASS.TOC FROM SCC_CALC_PASS ORDER BY TOC;     --1/6   PASS 6400

SELECT TOC FROM SCC_ACT_FMSEG WHERE SCC_ACT_FMSEG.TOC >= to_date('2021-11-24', 'yyyy-mm-dd') AND 
SCC_ACT_FMSEG.SEG_NO = 1 ORDER  BY TOC;

SELECT TOC FROM AP_STRIP_PDI  WHERE AP_STRIP_PDI.TOC >= to_date('2021-11-24', 'yyyy-mm-dd')  ORDER  BY TOC;

SELECT                ----------------------组合
	S.STRIPNO,
	AVG(S.SEG_NO) AS S_SEG_NO,
	AVG(S.SFC) AS S_SFC,
	AVG(S.FM_THICK) AS S_FM_THICK,
	AVG(S.FMOUTTHICK) AS S_FMOUTTHICH,
	LISTAGG(S.ROLL_FORCE,',') AS S_ROLL_FORCE,
	LISTAGG(S.CORR_FORCE_STAND,',') AS S_CORR_FORCE_STAND,
	LISTAGG(S.ROLL_SPEED,',') AS S_ROLL_SPEED,
	LISTAGG(S.ENTRY_THICK,',') AS S_ENTRY_THICK,
	LISTAGG(S.EXIT_THICK,',') AS S_EXIT_THICK,
	LISTAGG(S.ENTRY_TEMP,',') AS S_ENTRY_TEMP,
	AVG(S.FMTEMP) AS S_FMTEMP,
	LISTAGG(S.STRIP_WIDTH,',') AS S_STRIP_WIDTH,
	LISTAGG(S.ROLLGAP_SET,',') AS S_ROLLGAP_SET,
	LISTAGG(S.ROLLGAP_TRUE,',') AS S_ROLLGAP_TRUE,
	LISTAGG(S.MILLSTRETCH_ROLL,',') AS S_MILLSTRETCH_ROLL,
	LISTAGG(S.CORR_ZEROPOINT,',') AS S_CORR_ZEROPOINT,
	LISTAGG(S.ROLLWEAR,',') AS S_ROLLWEAR,
--	AVG(S.INHER_STRIPNO_ROLLFORCE) AS S_INHER_STRIPNO_ROLLFORCE,
	S.UNIX_TOC AS S_UNIX_TOC,---------------------------------------------------
	S.FMOUTWIDTH AS S_FMOUTWIDTH
FROM
	(
	SELECT
		PDI.STRIPNO ,
		act.SEG_NO ,
		ROLLFORCE.STAND_NO ,
		PDI.SFC ,
		ACT.FM_THICK ,
		PDI.FMOUTTHICK ,
		ROLLFORCE.ROLL_FORCE ,
		ROLLFORCE.CORR_FORCE_STAND ,
		ROLLFORCE.ENTRY_THICK ,
		ROLLFORCE.EXIT_THICK ,
		ROLLFORCE.ENTRY_TEMP ,
		GAP.ROLL_SPEED ,
		GAP.STRIP_WIDTH ,
		GAP.ROLLGAP_SET ,
		GAP.ROLLGAP_TRUE ,
		GAP.MILLSTRETCH_ROLL ,
		GAP.ROLLWEAR ,
		GAP.CORR_ZEROPOINT ,
		PDI.FMOUTWIDTH ,
		PDI.FMTEMP,
		TIMESTAMPDIFF(2,CHAR(TIMESTAMP(ACT.TOC)-TIMESTAMP('2021-06-01 08:00:00'))) AS UNIX_TOC
	FROM
			AP_STRIP_PDI PDI,
			SCC_CALC_ROLLFORCE ROLLFORCE,
			SCC_CALC_ROLLGAP GAP,
			SCC_CALC_TEMP TEMP,
			SCC_ACT_FMSEG ACT
	WHERE
			ROLLFORCE.STRIP_NO = PDI.STRIPNO
		AND GAP.STRIP_NO = PDI.STRIPNO
		AND TEMP.STRIP_NO = PDI.STRIPNO
		AND ACT.STRIP_NO = PDI.STRIPNO
		AND ACT.SEG_NO = 1
		AND GAP.STAND_NO = ROLLFORCE.STAND_NO
		AND TEMP.STAND_NO = GAP.STAND_NO
		ORDER BY ACT.TOC
	) AS S 
GROUP BY
		S.STRIPNO,S.UNIX_TOC,S.FMOUTWIDTH
		
		
		
		
--%stripno	streelgrade	sfcgrade	qualityno	thickclass	widthclass	
--%stand_no	calc_force	post_force	act_force	targthcik	thick1	thick2	thick3	thick4
		
SELECT 
PDI.SFC sfcgrade,
PDI.QUALITYNO qualityno,
FMSTRIP.THICK_CLASS thickclass,
FMSTRIP.WIDTH_CLASS widthclass,
POSTFORCE.STAND_NO stand_no,
CALFORCE.ROLL_FORCE calc_force,
POSTFORCE.ROLL_FORCE post_force,
(SUB.FORCE+SUB.FORCE_WS)  act_force,
PDI.FMOUTTHICK targthcik,
ACT.FM_THICK thick1,
ACT.FM_SNAP_THICK  thick2,
ACT.FM_THICK thick3,
ACT.FM_SNAP_THICK  thick4
FROM AP.AP_STRIP_PDI  AS PDI 
JOIN AP.SCC_FMSTRIP AS FMSTRIP  ON  FMSTRIP.STRIP_NO = PDI.STRIPNO 
JOIN AP.SCC_ACT_FMSEG AS ACT ON act.SEG_NO = 1 AND ACT.STRIP_NO = PDI.STRIPNO AND (ACT.STRIP_NO = '220147402300' OR ACT.STRIP_NO = '220147900100')
JOIN AP.SCC_CALC_ROLLFORCE AS CALFORCE ON CALFORCE.STRIP_NO =PDI.STRIPNO 
JOIN AP.SCC_POST_ROLLGAP AS postroll ON postroll.STRIP_NO = pdi.STRIPNO AND postroll.STAND_NO = calforce.STAND_NO AND postroll.SEG_NO = act.SEG_NO
JOIN AP.SCC_POST_ROLLFORCE AS POSTFORCE ON  postforce.STRIP_NO = pdi.STRIPNO  AND postforce.SEG_NO = act.SEG_NO AND postforce.STAND_NO =calforce.STAND_NO 
JOIN AP.SCC_ACT_FMSEGACT_SUB AS SUB ON SUB.STRIP_NO = pdi.STRIPNO AND SUB.SEG_NO =act.SEG_NO AND SUB.STAND_NO = calforce.STAND_NO 
JOIN AP.SCC_POST_TEMP AS POSTTEMP ON POSTTEMP.STRIP_NO =PDI.STRIPNO AND POSTTEMP.STAND_NO =CALFORCE.STAND_NO  AND POSTTEMP.SEG_NO =ACT.SEG_NO 
JOIN AP.SCC_CALC_TEMP AS CALTEMP ON CALTEMP.STRIP_NO =PDI.STRIPNO AND CALTEMP.STAND_NO =CALFORCE.STAND_NO
ORDER BY PDI.TOC ,  PDI.STRIPNO , CALFORCE.STAND_NO
		
		
		
		
		
		
		