SELECT PDI.STRIPNO,
       SUB.STAND_NO,
    (CF.ROLL_FORCE - (SUB.FORCE + SUB.FORCE)) / (SUB.FORCE + SUB.FORCE)              DETAL_FORCE,
    CF.CORR_FORCE_STAND -PF.CORR_FORCE_STAND                                         CORR_FORCE_DELTA,
      PF.STRIP_SPEED - CF.STRIP_SPEED                                                  DELTA_SPEED,
       PF.REL_REDU - CF.REL_REDU                                                        DELTA_REDU,

       ACT.FM_TEMP - CF.EXIT_TEMP                                                       F6_TEMP_DELTA,
       ACT.FM_TEMP - PF.EXIT_TEMP                                                       TEMP_CORR,
       RM.RM_EXIT_TEMP - PDI.R2TEMP                                                     RM_TEMP_DELTA,
       CF.ENTRY_TEMP                                                                    ENTRY_TEMP,
       RM.FET_ACT_TEMP,
       ACT.DESC_F1,
       ACT.DESC_F1 - PS.DESCF12_ON,
       ACT.DESC_F2 - PS.DESCF23_ON,
       PT.WATER_FLOW - CT.WATER_FLOW,

       CF.ENTRY_THICK,
       CF.ENTRY_TENSION,
       PG.CORR_ZEROPOINT_USE,
       PG.CORR_ZEROPOINT_USE - PG.CORR_ZEROPOINT,
       PG.MILLSTRETCH_ROLL,
       PG.ROLLGAP_OILROLL,
       PG.ROLLWEAR,

       TIMESTAMPDIFF(2, CHAR(TIMESTAMP(ACT.TOM) - TIMESTAMP('2021-06-01 08:00:00'))) AS UNIX_TIME,
       PS.ROLLEDSEQ,
       PS.THICK_CLASS

FROM AP.AP_STRIP_PDI AS PDI,
     AP.SCC_ACT_FMSEGACT_SUB AS SUB,
     AP.SCC_ACT_FMSEG AS ACT,
     AP.SCC_CALC_ROLLFORCE AS CF,
     AP.SCC_POST_ROLLFORCE AS PF,
     AP.SCC_CALC_ROLLGAP AS CG,
     AP.SCC_POST_ROLLGAP AS PG,
     AP.SCC_FMSTRIP AS SF,
     AP.SCC_CALC_ENTERTABLE AS RM,
     AP.SCC_CALC_PASS AS PS,
     AP.SCC_CALC_TEMP CT,
     AP.SCC_POST_TEMP PT
WHERE PDI.STRIPNO LIKE '220%'
--   AND SUB.STAND_NO = 1
  AND SUB.SEG_NO = 1
  AND SUB.STRIP_NO = PDI.STRIPNO
  AND ACT.SEG_NO = SUB.SEG_NO
  AND ACT.STRIP_NO = PDI.STRIPNO
  AND CF.STRIP_NO = PDI.STRIPNO
  AND PF.STRIP_NO = PDI.STRIPNO
  AND PF.SEG_NO = SUB.SEG_NO
  AND CG.STRIP_NO = PDI.STRIPNO
  AND PG.STRIP_NO = PDI.STRIPNO
  AND PG.SEG_NO = SUB.SEG_NO
  AND SF.STRIP_NO = PDI.STRIPNO
  AND SUB.STAND_NO = PF.STAND_NO
  AND CF.STAND_NO = PF.STAND_NO
  AND PG.STAND_NO = PF.STAND_NO
  AND CG.STAND_NO = PF.STAND_NO
  AND PDI.STRIPNO = RM.STRIP_NO
  AND RM.SEG_NO = SUB.SEG_NO
  AND PS.STRIPNO = PDI.STRIPNO
  AND CT.STRIP_NO = CF.STRIP_NO
  AND CT.STAND_NO = CF.STAND_NO
  AND SUB.SEG_NO = PT.SEG_NO
  AND SUB.STAND_NO = PT.STAND_NO
  AND SUB.STRIP_NO = PT.STRIP_NO
ORDER BY ACT.TOM, CF.STAND_NO;



SELECT AP.AP_STRIP_PDI.STRIPNO
FROM AP.SCC_FMSTRIP,
     AP.AP_STRIP_PDI
WHERE AP.AP_STRIP_PDI.TOM < (SELECT TOM FROM AP.AP_STRIP_PDI PDI WHERE PDI.STRIPNO = '220146903900')
  AND AP.AP_STRIP_PDI.SFC = (SELECT SFC FROM AP.AP_STRIP_PDI PDI WHERE PDI.STRIPNO = '220146903900')
  AND AP.SCC_FMSTRIP.THICK_CLASS = (SELECT THICK_CLASS FROM AP.SCC_FMSTRIP FM WHERE FM.STRIP_NO = '220146903900')
  AND AP.SCC_FMSTRIP.TEMP_CLASS = (SELECT TEMP_CLASS FROM AP.SCC_FMSTRIP FM WHERE FM.STRIP_NO = '220146903900')
  AND AP.SCC_FMSTRIP.WIDTH_CLASS = (SELECT WIDTH_CLASS FROM AP.SCC_FMSTRIP FM WHERE FM.STRIP_NO = '220146903900')
  AND AP.SCC_FMSTRIP.STRIP_NO = AP.AP_STRIP_PDI.STRIPNO;



SELECT CF.STRIP_NO,
       ACT.FM_THICK - PDI.FMOUTTHICK                                       delta_thick,
       CF.STAND_NO,
       PDI.SFC,
       PDI.QUALITYNO,
       SF.THICK_CLASS,
       SF.WIDTH_CLASS,
       SF.TEMP_CLASS,
       ACT.FM_THICK,
       PDI.FMOUTTHICK,
       PDI.FMOUTTHICKTOLPLUS,
       CF.EXIT_THICK                                                       EXIT_THICK_CAL,
       PG.CORR_ZEROPOINT_USE,
       PG.CORR_ZEROPOINT,
       SUB.FORCE + SUB.FORCE_WS                                            SUM_FORCE,
       CF.ROLL_FORCE                                                       ROLL_FORCE_CAL,
       PF.ROLL_FORCE                                                       ROLL_FORCE_POST,
       (CF.ROLL_FORCE - (SUB.FORCE + SUB.FORCE)) / (SUB.FORCE + SUB.FORCE) DETAL_FORCE,
       CF.CORR_FORCE_STAND                                                 CORR_FORCE_STAND_CAL,
       PF.CORR_FORCE_STAND                                                 CORR_FORCE_STAND_POST,
       CF.EXIT_TEMP EXIT_TEMP_CAL,
       ACT.FM_TEMP,
       PF.EXIT_TEMP EXIT_TEMP_POST,
       ACT.TOM
FROM AP.AP_STRIP_PDI AS PDI,
     AP.SCC_ACT_FMSEGACT_SUB AS SUB,
     AP.SCC_ACT_FMSEG AS ACT,
     AP.SCC_CALC_ROLLFORCE AS CF,
     AP.SCC_POST_ROLLFORCE AS PF,
     AP.SCC_CALC_ROLLGAP AS CG,
     AP.SCC_POST_ROLLGAP AS PG,
     AP.SCC_FMSTRIP SF
WHERE
    PDI.STRIPNO = '220153200500'
  AND
    SUB.SEG_NO = 1
  AND SUB.STRIP_NO = PDI.STRIPNO
  AND ACT.SEG_NO = SUB.SEG_NO
  AND ACT.STRIP_NO = PDI.STRIPNO
  AND CF.STRIP_NO = PDI.STRIPNO
  AND PF.STRIP_NO = PDI.STRIPNO
  AND PF.SEG_NO = SUB.SEG_NO
  AND CG.STRIP_NO = PDI.STRIPNO
  AND PG.STRIP_NO = PDI.STRIPNO
  AND PG.SEG_NO = SUB.SEG_NO
  AND SF.STRIP_NO = PDI.STRIPNO
  AND SUB.STAND_NO = PF.STAND_NO
  AND CF.STAND_NO = PF.STAND_NO
  AND PG.STAND_NO = PF.STAND_NO
  AND CG.STAND_NO = PF.STAND_NO
ORDER BY ACT.TOM, CF.STAND_NO