--STRIP_NO    |STAND_NO|SFC  |QUAL_NO|
--THICK_CLASS|WIDTH_CLASS|FM_THICK_ACT|
--FMOUTTHICK |FMOUTTHICKTOLPLUS|
--EXIT_THICK_CAL|CORR_ZEROPOINT_USE|CORR_ZEROPOINT
--|FORCE      |FORCE_WS   |SUM_FORCE  |ROLL_FORCE_CAL
--|ROLL_FORCE_POST|DETAL_FORCE |CORR_FORCE_STAND_CAL|
--CORR_FORCE_STAND_POST|ROLL_DIAM_POST|CIRC_SPEED |KM_POST    |
--FM_TEMP_ACT|EXIT_TEMP_POST|TOC             |delta_thick|delta_force|

SELECT CF.STRIP_NO ,ACT.FM_THICK - PDI.FMOUTTHICK delta_thick,CF.STAND_NO ,PDI.SFC,
PDI.QUALITYNO ,SF.THICK_CLASS ,SF.WIDTH_CLASS ,SF.TEMP_CLASS ,
ACT.FM_THICK ,PDI.FMOUTTHICK ,PDI.FMOUTTHICKTOLPLUS ,CF.EXIT_THICK EXIT_THICK_CAL,
PG.CORR_ZEROPOINT_USE ,PG.CORR_ZEROPOINT,SUB.FORCE + SUB.FORCE_WS SUM_FORCE,
CF.ROLL_FORCE ROLL_FORCE_CAL,PF.ROLL_FORCE ROLL_FORCE_POST,
(CF.ROLL_FORCE-(SUB.FORCE + SUB.FORCE))/(SUB.FORCE + SUB.FORCE) DETAL_FORCE,
CF.CORR_FORCE_STAND CORR_FORCE_STAND_CAL,PF.CORR_FORCE_STAND CORR_FORCE_STAND_POST,
CF.EXIT_TEMP ,ACT.FM_TEMP ,PF.EXIT_TEMP ,ACT.TOM
FROM AP.AP_STRIP_PDI AS PDI , AP.SCC_ACT_FMSEGACT_SUB AS SUB , AP.SCC_ACT_FMSEG AS ACT, 
AP.SCC_CALC_ROLLFORCE AS CF , AP.SCC_POST_ROLLFORCE AS PF , AP.SCC_CALC_ROLLGAP AS CG ,
AP.SCC_POST_ROLLGAP AS PG , AP.SCC_FMSTRIP SF
WHERE PDI.STRIPNO = '220146903900' AND SUB.SEG_NO = 1 AND SUB.STRIP_NO = PDI.STRIPNO 
AND ACT.SEG_NO = SUB.SEG_NO AND ACT.STRIP_NO = PDI.STRIPNO 
AND CF.STRIP_NO = PDI.STRIPNO AND PF.STRIP_NO = PDI.STRIPNO  AND PF.SEG_NO = SUB.SEG_NO 
AND CG.STRIP_NO = PDI.STRIPNO AND PG.STRIP_NO = PDI .STRIPNO AND PG.SEG_NO = SUB.SEG_NO 
AND SF.STRIP_NO = PDI.STRIPNO 
AND SUB.STAND_NO = PF.STAND_NO AND CF.STAND_NO = PF.STAND_NO AND PG.STAND_NO = PF.STAND_NO 
AND CG.STAND_NO = PF.STAND_NO 
ORDER BY ACT.TOM,CF.STAND_NO 





SELECT AP.AP_STRIP_PDI.STRIPNO FROM AP.SCC_FMSTRIP , AP.AP_STRIP_PDI WHERE  AP.AP_STRIP_PDI.TOM < (SELECT TOM FROM AP.AP_STRIP_PDI PDI WHERE PDI.STRIPNO = '220146903900')
AND AP.AP_STRIP_PDI.SFC = (SELECT SFC FROM AP.AP_STRIP_PDI PDI WHERE PDI.STRIPNO = '220146903900') 
AND AP.SCC_FMSTRIP.THICK_CLASS  = (SELECT THICK_CLASS FROM AP.SCC_FMSTRIP FM WHERE FM.STRIP_NO = '220146903900') 
AND AP.SCC_FMSTRIP.TEMP_CLASS  = (SELECT TEMP_CLASS FROM AP.SCC_FMSTRIP FM WHERE FM.STRIP_NO = '220146903900') 
AND AP.SCC_FMSTRIP.WIDTH_CLASS  = (SELECT WIDTH_CLASS  FROM AP.SCC_FMSTRIP FM WHERE FM.STRIP_NO = '220146903900') 
AND AP.SCC_FMSTRIP.STRIP_NO  = AP.AP_STRIP_PDI.STRIPNO  










SELECT CF.STRIP_NO ,ACT.FM_THICK - PDI.FMOUTTHICK delta_thick,CF.STAND_NO ,PDI.SFC,  PDI.QUALITYNO ,SF.THICK_CLASS ,SF.WIDTH_CLASS ,SF.TEMP_CLASS ,  ACT.FM_THICK ,PDI.FMOUTTHICK ,PDI.FMOUTTHICKTOLPLUS ,CF.EXIT_THICK EXIT_THICK_CAL,  PG.CORR_ZEROPOINT_USE ,PG.CORR_ZEROPOINT,SUB.FORCE + SUB.FORCE_WS SUM_FORCE,  CF.ROLL_FORCE ROLL_FORCE_CAL,PF.ROLL_FORCE ROLL_FORCE_POST,  (CF.ROLL_FORCE-(SUB.FORCE + SUB.FORCE))/(SUB.FORCE + SUB.FORCE) DETAL_FORCE,  CF.CORR_FORCE_STAND CORR_FORCE_STAND_CAL,PF.CORR_FORCE_STAND CORR_FORCE_STAND_POST,  CF.EXIT_TEMP ,ACT.FM_TEMP ,PF.EXIT_TEMP ,ACT.TOM  FROM AP.AP_STRIP_PDI AS PDI , AP.SCC_ACT_FMSEGACT_SUB AS SUB , AP.SCC_ACT_FMSEG AS ACT,   AP.SCC_CALC_ROLLFORCE AS CF , AP.SCC_POST_ROLLFORCE AS PF , AP.SCC_CALC_ROLLGAP AS CG ,  AP.SCC_POST_ROLLGAP AS PG , AP.SCC_FMSTRIP SF  WHERE PDI.STRIPNO = '220146903900' AND SUB.SEG_NO = 1 AND SUB.STRIP_NO = PDI.STRIPNO   AND ACT.SEG_NO = SUB.SEG_NO AND ACT.STRIP_NO = PDI.STRIPNO   AND CF.STRIP_NO = PDI.STRIPNO AND PF.STRIP_NO = PDI.STRIPNO  AND PF.SEG_NO = SUB.SEG_NO   AND CG.STRIP_NO = PDI.STRIPNO AND PG.STRIP_NO = PDI .STRIPNO AND PG.SEG_NO = SUB.SEG_NO   AND SF.STRIP_NO = PDI.STRIPNO   AND SUB.STAND_NO = PF.STAND_NO AND CF.STAND_NO = PF.STAND_NO AND PG.STAND_NO = PF.STAND_NO   AND CG.STAND_NO = PF.STAND_NO   ORDER BY ACT.TOM,CF.STAND_NO