SELECT
	SCC_POST_TEMP.STRIP_NO ,
	SCC_POST_TEMP.STAND_NO ,
	AP_STRIP_PDI.SFC ,
	AP_STRIP_PDI.FMOUTTHICK ,
	AP_STRIP_PDI.FMTEMP, 
	SCC_POST_TEMP.ENTRY_TEMP ,
	SCC_POST_TEMP.AIR_COOL_TIME ,
	SCC_ACT_FMSEGACT_SUB.SPEED,
	SCC_POST_ROLLFORCE.REL_REDU ,
	SCC_POST_ROLLFORCE.ENTRY_THICK,  --±‰–Œ
	SCC_CALC_ENTERTABLE.RM_EXIT_TEMP,
	SCC_CALC_ENTERTABLE.ARRIVE_TIME , --ø’¿‰
	SCC_CALC_ENTERTABLE.FET_ACT_TEMP, --ø’¿‰
	SCC_ACT_FMSEG.DESC_F1 ,
	SCC_ACT_FMSEG.DESC_F2 ,
	SCC_ACT_FMSEGACT_SUB.WATER_FLOW,
	SCC_ACT_FMSEGACT_SUB.FORCE+SCC_ACT_FMSEGACT_SUB.FORCE_WS AS FORCE,
	SCC_CALC_TEMP.EXIT_TEMP CAL,
	SCC_POST_TEMP.EXIT_TEMP POST,
	SCC_ACT_FMSEG.FM_TEMP
FROM
	AP.SCC_POST_TEMP SCC_POST_TEMP,
	AP.SCC_ACT_FMSEGACT_SUB SCC_ACT_FMSEGACT_SUB,
	AP.SCC_ACT_FMSEG SCC_ACT_FMSEG,
	AP.SCC_POST_ROLLFORCE SCC_POST_ROLLFORCE,
	AP.SCC_CALC_ENTERTABLE SCC_CALC_ENTERTABLE,
	AP.SCC_CALC_TEMP SCC_CALC_TEMP,
	AP.AP_STRIP_PDI AP_STRIP_PDI
WHERE
	SCC_POST_TEMP.SEG_NO = 1
	AND SCC_ACT_FMSEGACT_SUB.SEG_NO = SCC_POST_TEMP.SEG_NO
	AND SCC_ACT_FMSEGACT_SUB.STAND_NO = SCC_POST_TEMP.STAND_NO
	AND SCC_ACT_FMSEGACT_SUB.STRIP_NO = SCC_POST_TEMP.STRIP_NO
	AND SCC_ACT_FMSEG.STRIP_NO = SCC_POST_TEMP.STRIP_NO
	AND SCC_ACT_FMSEG.SEG_NO = SCC_POST_TEMP.SEG_NO
	AND SCC_POST_ROLLFORCE.SEG_NO = SCC_POST_TEMP.SEG_NO
	AND SCC_POST_ROLLFORCE.STAND_NO = SCC_POST_TEMP.STAND_NO
	AND SCC_POST_ROLLFORCE.STRIP_NO  = SCC_POST_TEMP.STRIP_NO
	AND SCC_CALC_ENTERTABLE.STRIP_NO = SCC_POST_ROLLFORCE.STRIP_NO
	AND SCC_CALC_ENTERTABLE.SEG_NO  = SCC_POST_ROLLFORCE.SEG_NO
--	AND SCC_POST_TEMP.TOC <= to_date('2021-10-02', 'yyyy-mm-dd')
--	AND SCC_POST_TEMP.TOC >= to_date('2021-10-01', 'yyyy-mm-dd')
	AND SCC_CALC_TEMP.STRIP_NO = SCC_POST_TEMP.STRIP_NO
	AND SCC_CALC_TEMP.STAND_NO = SCC_POST_TEMP.STAND_NO 
	AND AP_STRIP_PDI.STRIPNO = SCC_POST_ROLLFORCE.STRIP_NO
	ORDER BY  SCC_POST_TEMP.STRIP_NO ,SCC_POST_TEMP.STAND_NO 
	
	
--	TIMESTAMPDIFF(2,CHAR(TIMESTAMP(SCC_POST_TEMP.TOC)-TIMESTAMP('2021-06-01 08:00:00'))) AS UNIX_TIME,
	
	
SELECT SFC,COUNT(SFC) C	FROM AP_STRIP_PDI  GROUP BY SFC ORDER BY C DESC;
	
CREATE TABLE THICK_SCALE;

