SELECT pdi.STRIPNO STRIP_NO,CALFORCE.STAND_NO ,pdi.sfc SFC,pdi.QUALITYNO QUAL_NO,fmstrip.THICK_CLASS, fmstrip.WIDTH_CLASS ,fmstrip.TEMP_CLASS ,
SUB.SPEED ,
SUB.SCREW_DOWN,
ACT.FM_THICK ,
ACT.FM_WIDTH ,
POSTFORCE.STRIP_WIDTH,
POSTFORCE.ENTRY_THICK,
POSTFORCE.EXIT_THICK,
POSTFORCE.ROLL_DIAM,
POSTFORCE.CIRC_SPEED,
POSTFORCE.STRIP_SPEED,
POSTFORCE.ENTRY_TEMP,
POSTFORCE.EXIT_TEMP,
POSTFORCE.REL_REDU,
CALFORCE.ENTRY_TENSION ENTRY_TENSION_CAL,
CALFORCE.EXIT_TENSION EXIT_TENSION_CAL,
PDI.CARBON,PDI.SILICON,pdi.MANGANESE,
PDI.NIOBIUM,PDI.VANADIUM,PDI.TITANIUM,
SUB.FORCE+SUB.FORCE_WS FORCE,
to_char(PDI.TOC,'yyyy/mm/dd hh:mm:ss') TOC
FROM AP.AP_STRIP_PDI  AS PDI 
JOIN AP.SCC_FMSTRIP AS FMSTRIP  ON FMSTRIP.STRIP_NO =PDI.STRIPNO AND pDI.TOC<=to_date('2024-10-01','yyyy-mm-dd') AND pDI.TOC>=to_date('2021-01-02','yyyy-mm-dd')
JOIN AP.SCC_ACT_FMSEG AS ACT ON act.SEG_NO =3 AND ACT.STRIP_NO =PDI.STRIPNO 
JOIN AP.SCC_CALC_ROLLFORCE AS CALFORCE ON CALFORCE.STRIP_NO =PDI.STRIPNO AND (CALFORCE.STAND_NO < 8)
JOIN AP.SCC_POST_ROLLGAP AS postroll ON postroll.STRIP_NO = pdi.STRIPNO AND postroll.STAND_NO = calforce.STAND_NO AND postroll.SEG_NO = act.SEG_NO
JOIN AP.SCC_POST_ROLLFORCE AS POSTFORCE ON  postforce.STRIP_NO = pdi.STRIPNO  AND postforce.SEG_NO = act.SEG_NO AND postforce.STAND_NO =calforce.STAND_NO 
JOIN AP.SCC_ACT_FMSEGACT_SUB AS SUB ON SUB.STRIP_NO = pdi.STRIPNO AND SUB.SEG_NO =act.SEG_NO AND SUB.STAND_NO = calforce.STAND_NO 
JOIN AP.SCC_POST_TEMP AS POSTTEMP ON POSTTEMP.STRIP_NO =PDI.STRIPNO AND POSTTEMP.STAND_NO =CALFORCE.STAND_NO  AND POSTTEMP.SEG_NO =ACT.SEG_NO 
JOIN AP.SCC_CALC_TEMP AS CALTEMP ON CALTEMP.STRIP_NO =PDI.STRIPNO AND CALTEMP.STAND_NO =CALFORCE.STAND_NO
JOIN AP.AP_STRIP_STATIS AS STATIS ON STATIS.ITEM = 'tempR2Exit' AND  STATIS.STRIPNO  = PDI.STRIPNO 
JOIN AP.RMC_ACT_RMPASS   AS PASS ON PASS.STRIPNO  = PDI.STRIPNO AND PASS.STANDNO =2 AND PASS.PASSNO  = 3 
JOIN AP.RMC_ACT_R2LAST AS R2LAST ON  R2LAST .STRIPNO =PDI.STRIPNO 
ORDER BY PDI.TOC ,  PDI.STRIPNO , CALFORCE.STAND_NO

