SELECT
	PDI.STRIPNO,
	POST_ROLL.STAND_NO ,
	PDI.STEELGRADE ,
	FM.THICK_CLASS ,
	FM.TEMP_CLASS,
	CAL_ROLL.ROLLWEAR ,
	POST_ROLL.ROLLWEAR ,
	POST_ROLL.CORR_ZEROPOINT_USE,
	POST_ROLL.CORR_ZEROPOINT,
	CAL_ROLL.ROLLGAP_ZERO,
	POST_ROLL.ROLLGAP_ZERO,
	CAL_ROLL.ROLLGAP_TRUE,
	POST_ROLL.ROLLGAP_TRUE,
	POST_ROLL.WS_GAP_FBK,
	TIMESTAMPDIFF(2, CHAR(TIMESTAMP(CAL_ROLL.TOC)-TIMESTAMP('2021-06-01 08:00:00'))) AS UNIX_TIME
FROM
	AP.AP_STRIP_PDI AS PDI,
	AP.SCC_FMSTRIP AS FM,
	AP.SCC_CALC_ROLLGAP AS CAL_ROLL,
	AP.SCC_POST_ROLLGAP AS POST_ROLL
WHERE
	FM.STRIP_NO = PDI.STRIPNO
	AND CAL_ROLL.STRIP_NO = PDI.STRIPNO
	AND POST_ROLL.STRIP_NO = CAL_ROLL.STRIP_NO
	AND POST_ROLL.STAND_NO = CAL_ROLL.STAND_NO AND POST_ROLL.SEG_NO = 2 
ORDER BY STRIPNO ,STAND_NO
